### PR TITLE
ADD GRE figure & update captions

### PR DESCRIPTION
**Pull request by agahkarakuzu**
Changes requested by @dpapp86 

* Add new Figure 
* Add new caption
* Update Figure labels

### CODE REVIEW

**Comment by dpapp86** [comment]
Having run the new file, it does produce the expected output.

Good to go from my point of view

**Comment by dpapp86** [comment]
Not quite. The y-scale of the CSF/SC contrast + B1+ efficiency figure is now not the same for all subjects, see issue here: #101

**Comment by agahkarakuzu** [comment]
@dpapp86 I've pushed the commit for fixing y axes range.

**Comment by agahkarakuzu** [comment]
Yup, all these changes are pushed here.

**Comment by dpapp86** [comment]
Just in case you did not see my edit:

Anything I need to do? I am not a reviewer on this PR, so I can't OK the merge.

**Review by dpapp86 — COMMENTED** [review]
Works as advertised

**Review by dpapp86 — APPROVED** [review]

**Pull request merged**
