### PR TITLE
Compute cord/CSF ratio and removing T1w bloc

### PR DESCRIPTION
**Pull request by jcohenadad**
This PR removes the analysis of the T1w scans, given their poor relevance for the RF shimming paper. Instead, we introduce the computation of the cord/CSF ratio.

- Fixes https://github.com/shimming-toolbox/rf-shimming-7t/issues/63

### CODE REVIEW

**Comment by jcohenadad** [comment]
Encouraging preliminary results from [c598978](https://github.com/shimming-toolbox/rf-shimming-7t/pull/64/commits/c5989786f3da69527f021950bf5017f4def8cdbc): 

download

**Comment by dpapp86** [comment]
Reopening this issue so I can comment.

1, This now changes the argument from one based on signal intensity to one based on contrast. In this case, going for the CNR may be better?
2, It is hard to interpret, for example, the results for sub-03 (increase-decrease-increase), especially in light of the otherwise easier to interpret signal intensity within the CS itself
3, While I did some spot checks to see if the mask used for RF shim calculation does include all of the CSF on later scans (where we would expect more motion wrt the noshim case), this is not guaranteed, as it was not part of the experimental design. If in some slices, the VOI for RF shimming does _not_ include the CSF, this might bias results
4, The optimisation algorithm was not "make the CNR between CSF and SC the best i could be", it was "make the B1+ field in the mask as homogeneous/high/etc as it can be". I am not sure one translates easily to the other.
5. B1- is a straight multiplicative field (at first approximation), and is, bar inter-scan motion, the same for all scans.

**Comment by jcohenadad** [comment]
> 1, This now changes the argument from one based on signal intensity to one based on contrast. In this case, going for the CNR may be better?

what we are really after is more homogeneous Tx, which means more homogeneous flip angle, which means more homogeneous contrast between two structures having a drastically different T1 (eg: CSF and SC). So to me, looking at the ratio makes much more sense.

> 2, It is hard to interpret, for example, the results for sub-03 (increase-decrease-increase), especially in light of the otherwise easier to interpret signal intensity within the CS itself

these are preliminary results-- hindered by #35 

> 3, While I did some spot checks to see if the mask used for RF shim calculation does include all of the CSF on later scans (where we would expect more motion wrt the noshim case), this is not guaranteed, as it was not part of the experimental design. If in some slices, the VOI for RF shimming does not include the CSF, this might bias results

given the size of the Tx coils and their distance from the cord/CSF, this makes a negligible difference

> 4, The optimisation algorithm was not "make the CNR between CSF and SC the best i could be", it was "make the B1+ field in the mask as homogeneous/high/etc as it can be". I am not sure one translates easily to the other.

right, see point 1

> 5. B1- is a straight multiplicative field (at first approximation), and is, bar inter-scan motion, the same for all scans.

right, but looking at curves that tell multiple stories is less straightforward than curves that only tell one story

> 6, Please give me an @ next time before pushing through a PR of this magnitude, especially considering time zone differences.

yes, sorry. In any case, if you are in any disagreement, it is very straightforward to revert changes with git. Conversation can always happen _after the fact_, and we can checkout a previous commit if we decide to. This is exactly the reason why working with atomic PR, addressing only a single issue, makes it easier to navigate the project in time in a collaborative manner.

**Comment by dpapp86** [comment]
Let's revisit after #35 is fixed, in this case.

**Pull request merged**
