### PR TITLE
Added in B1+ map visualisation.

### PR DESCRIPTION
**Pull request by dpapp86**
Added B1+ map visualisation:
 
image

Solves #44 

Adding the color bar messes with the vertical spacing a bit, but I have left it as is for the sake of generating it all in one figure.

Everything else has been left untouched

Please review @jcohenadad

### CODE REVIEW

**Review by jcohenadad — COMMENTED** [review]
Reviewing code right now-- adding a few commits-- feel free to comment on them

**Comment by jcohenadad** [comment]
My output image looks a bit different than the one in https://github.com/shimming-toolbox/rf-shimming-7t/pull/72#issue-2092834918

image

Notably, it looks like the subject is not the same. My suspicion is that sub-05 was selected in https://github.com/shimming-toolbox/rf-shimming-7t/pull/72#issue-2092834918 because of https://github.com/shimming-toolbox/rf-shimming-7t/pull/72/commits/56f7cfa572db740b6b131344f92b03fd5fec3ed6. 

Indeed, when selecting sub-05, the images match:

image

**Review by jcohenadad — COMMENTED** [review]
Instead of showing the cord seg (little scientific value), I suggest we show the actual mask that was used for the RF shimming. I'll work on that

**Comment by jcohenadad** [comment]
Just putting out there for discussion: do we want to show the unmasked B1+ maps?

image

meh, no. I prefer the masked ones

**Comment by jcohenadad** [comment]
Updated colormap range:

image

**Comment by jcohenadad** [comment]
Adding colorbar legend https://github.com/shimming-toolbox/rf-shimming-7t/pull/72/commits/effbae567673ee3994031ed9ee540e14a6f5556f:

download-1

**Comment by jcohenadad** [comment]
Show mask edge instead [21e5305](https://github.com/shimming-toolbox/rf-shimming-7t/pull/72/commits/21e5305b00224715efd73ae8623bcf570f7eeac1):

download-2

**Comment by dpapp86** [comment]
> Show mask edge instead [21e5305](https://github.com/shimming-toolbox/rf-shimming-7t/pull/72/commits/21e5305b00224715efd73ae8623bcf570f7eeac1):
> 

I like this one best!

(I think I did the tresholding on the mask itself because it created a grey, rather than transparent overlay, and that got rid of it).

**Comment by jcohenadad** [comment]
Further cosmetic tweaking [9228e72](https://github.com/shimming-toolbox/rf-shimming-7t/pull/72/commits/9228e7226efc782e1e04180524e1207a7f626d31):

image

**Comment by jcohenadad** [comment]
Show more S-I extent [242e7d2](https://github.com/shimming-toolbox/rf-shimming-7t/pull/72/commits/242e7d22885cf3a7c52c58fd652dc37073f27b90):

download-5

**Review by jcohenadad — APPROVED** [review]
@dpapp86 Are we happy with https://github.com/shimming-toolbox/rf-shimming-7t/pull/72/commits/242e7d22885cf3a7c52c58fd652dc37073f27b90?

**Comment by dpapp86** [comment]
> @dpapp86 Are we happy with [242e7d2](https://github.com/shimming-toolbox/rf-shimming-7t/commit/242e7d22885cf3a7c52c58fd652dc37073f27b90)?


Oui.

**Pull request merged**
