### PR TITLE
Convert to NeuroLibre submission

### LINKED ISSUE #42: Steps towards a NeuroLibre pre-print publication
We plan to submit the manuscript as a preprint to NeuroLibre. In this issue we discuss what it takes, who is doing what, etc.

### PR DESCRIPTION
**Pull request by mathieuboudreau**
Resolves #42 

Live link to Jupyter Book: https://shimming-toolbox.github.io/rf-shimming-7t/

Currently all the working links point to this branch for the review so that they're usable and viewable, will need to change all instances of `mb/neurolibre` to `main` prior to merging.

https://github.com/shimming-toolbox/rf-shimming-7t/blob/c223bcacbaae78dc887c2c884d3464606babda2f/README.md?plain=1#L4-L5
https://github.com/shimming-toolbox/rf-shimming-7t/blob/c223bcacbaae78dc887c2c884d3464606babda2f/README.md?plain=1#L36
https://github.com/shimming-toolbox/rf-shimming-7t/blob/c223bcacbaae78dc887c2c884d3464606babda2f/README.md?plain=1#L45
https://github.com/shimming-toolbox/rf-shimming-7t/blob/c223bcacbaae78dc887c2c884d3464606babda2f/.github/workflows/main.yml#L7
https://github.com/shimming-toolbox/rf-shimming-7t/blob/efcdefa2c97e25bdff6bcd0a38ccf3d161aeb22e/content/_config.yml#L19
https://github.com/shimming-toolbox/rf-shimming-7t/blob/efcdefa2c97e25bdff6bcd0a38ccf3d161aeb22e/content/_config.yml#L19

Will also have to move this release binary of the processed data to this repo or somewhere else that's not GDrive (they hate it when you access files too often): 
https://github.com/shimming-toolbox/rf-shimming-7t/blob/c223bcacbaae78dc887c2c884d3464606babda2f/binder/data_requirement.json#L2

**or** if you prefer, we can keep all of this in this branch and submit to NeuroLibre using a branch reference.

After this is merged/ready, submitting to NeuroLibre is done through their portal (must log in with ORCID first): https://neurolibre.org. It's a quick 2 minute form to fill out.

### CODE REVIEW

**Comment by mathieuboudreau** [comment]
@jcohenadad just pinging you if the email for this PR slipped through the cracks

**Comment by jcohenadad** [comment]
> @jcohenadad just pinging you if the email for this PR slipped through the cracks

it's on my todo list, thank you for the reminder 😊

**Review by jcohenadad — COMMENTED** [review]
weird formatting of the ref:

image

**Comment by jcohenadad** [comment]
refs have multiples URLs-- i would keep only one per ref:

image

**Review by jcohenadad — COMMENTED** [review]
typo 'efficienty' on fig 1-- here is the updated version:
https://drive.google.com/drive/folders/10r99U3pxgudTo2JVgb7mHtqPXuNsLOO1

**Comment by jcohenadad** [comment]
it would be cool to have the fig interactive but i guess this is too time consuming to produce (tagging @nstikov so he is aware of user-facing perception of neurolibre notebook generation):

image

**Review by jcohenadad — COMMENTED** [review]
image

is the fig saving actually necessary? (it ends up in the server unused, right?)

**Review by jcohenadad — COMMENTED** [review]
In reference to https://github.com/shimming-toolbox/rf-shimming-7t/pull/91#pullrequestreview-1878409732, it would be great to use the fig generated by your notebook for the article. Notably because you fixed https://github.com/shimming-toolbox/rf-shimming-7t/issues/90 on this repos, but the issue is still present on the original repos (hence my frustration of having the two repos out of sync @nstikov))-- what would be the best way to do it to get figs at 300dpi?

**Comment by mathieuboudreau** [comment]
> weird formatting of the ref:
> 
> image

This is a Jupyter Book quirk because we’re using their bibtex rendering for the bibliographie, and @agahkarakuzu has told me before that we’re required to use this Jupyter Book biblio rendering for neurolibre submissions. The numbers indicate the different instances that the refs were cited in the text; to remove it I could limit to one citation instance per ref

**Comment by mathieuboudreau** [comment]
> it would be cool to have the fig interactive but i guess this is too time consuming to produce (tagging @nstikov so he is aware of user-facing perception of neurolibre notebook generation):
> 
> image

The challenge here is that I don’t think it would be possible to get an interactive Plotly figure that looks exactly this way. Plotly doesn’t have an image-visualizing tool; they refer users to their heatmap tool to display images/qMRI maps like this. The best I could achieve was to concatenate 2 subplots, but to do this with 8 may not work as desired.

**Comment by mathieuboudreau** [comment]
> In reference to [#91 (review)](https://github.com/shimming-toolbox/rf-shimming-7t/pull/91#pullrequestreview-1878409732), it would be great to use the fig generated by your notebook for the article. Notably because you fixed #90 on this repos, but the issue is still present on the original repos (hence my frustration of having the two repos out of sync @nstikov))-- what would be the best way to do it to get figs at 300dpi?

There’s an optional config that can be added to do this, i’ll let u know when its added with an example outputs (its not saved inside the script, but gives a displaybar that lets you save it to your configurated format)

**Comment by mathieuboudreau** [comment]
> do we want to use the same font as the rest of the fig for 'sub-01', etc.
> 
> image

Good catch, will fix these annotations

**Comment by jcohenadad** [comment]
> The challenge here is that I don’t think it would be possible to get an interactive Plotly figure that looks exactly this way. Plotly doesn’t have an image-visualizing tool; they refer users to their heatmap tool to display images/qMRI maps like this. The best I could achieve was to concatenate 2 subplots, but to do this with 8 may not work as desired.

no worries (and no need to spend time on this), i mostly wanted to give feedback for @nstikov

**Comment by mathieuboudreau** [comment]
@jcohenadad 

> In reference to [#91 (review)](https://github.com/shimming-toolbox/rf-shimming-7t/pull/91#pullrequestreview-1878409732), it would be great to use the fig generated by your notebook for the article. Notably because you fixed #90 on this repos, but the issue is still present on the original repos (hence my frustration of having the two repos out of sync @nstikov))-- what would be the best way to do it to get figs at 300dpi?

Updated the Plotly config to show a display bar to export a PNG:

Screenshot 2024-02-13 at 7 42 57 PM

From:  https://shimming-toolbox.github.io/rf-shimming-7t/

I've exported a version of the PNG,

<details>

Figure 3_plotly

</details>

and uploaded it to the the figures folder for the manuscript (link to figure: https://drive.google.com/file/d/10uSw0ct5VATOqHcgmj8mq3FHn6qnAYs8/view?usp=sharing). If good as is, we can delete the other fig3 files.

A few notes:

* Exporting a TIFF directly isn't possible through Plotly. If a *.tiff file is needed, you can simply rename the file (png->tiff work like that). Otherwise,
* By changing a setting (https://github.com/shimming-toolbox/rf-shimming-7t/blob/b48b12ba8dd21b50e03486f528290994b5a8b6b6/content/index.ipynb#L1277), we can let plotly export SVG's instead, and from here you could open the vector file in Inkscape/Illustrator and export it that way.
* In addition, the conversion process from Plotly to PNG/SVG isn't identical; there are some small differences in scaling/positionning due to whatever tool they use. If some minor resizing/moving is desired, this should be done via the SVG.
* The proportions of the image also requires a bit of guesswork; this is set via

https://github.com/shimming-toolbox/rf-shimming-7t/blob/b48b12ba8dd21b50e03486f528290994b5a8b6b6/content/index.ipynb#L1279-L1281

  changing the height/width will change the ratio, and the final number of pixels in your images will be these numbers times your scaling factor (which we set to 2 to give higher res; I find that setting the number of pixels higher directly doesn't give as good of a final image than doing it this way).

**Comment by mathieuboudreau** [comment]
@jcohenadad I believe I've addressed all of comments, you can have one more look here: https://shimming-toolbox.github.io/rf-shimming-7t/

Once you think this is ready for merging, I'll update all the references that point to this branch (see original post for this PR) at all locations to point to master (or is it main) instead, then it wll be ready for merging.

**Review by jcohenadad — APPROVED** [review]
beautiful work ❤️

**Pull request merged**
