### PR TITLE
Add CV metric for B1+ homogeneity

### PR DESCRIPTION
**Pull request by dpapp86**
Added CV calculation for B1+ maps

I do not know why the formatting is so screwed up.

### CODE REVIEW

**Review by jcohenadad — COMMENTED** [review]
the formatting drastically changes, making it hard to see the diff-- also, i am wondering if this is the latest file we should be modifying? with the neurolibre business happening in parallel i'm confused about the correct workflow-- @mathieuboudreau to the rescue 😅 

also see https://github.com/shimming-toolbox/rf-shimming-7t/pull/99/files#r1596216299

**Comment by dpapp86** [comment]
@agahkarakuzu 
and @mathieuboudreau to avoid parallelisation

Following up on your generous offer from #99:

For this one, the changes are:
In section 
**6     |     Process fmap/TFL (flip angle maps)**
Within Cell nr 5 of that heading (titled "_Prepare data for figure of B1+ values along the spinal cord across shim methods_")

**Replace** lines 99-102, which is this:
```
            # Compute stats on the non-resampled data (to avoid interpolation errors)
            mean_data = np.mean(wa_data)
            sd_data = np.std(wa_data)
            data_stats.append([subject, shim_mode, mean_data, sd_data])

```
With this:
```
            # Compute stats on the non-resampled data (to avoid interpolation errors)
            mean_data = np.mean(wa_data)
            sd_data = np.std(wa_data)
            CV_data= (sd_data/mean_data)*100
            data_stats.append([subject, shim_mode, mean_data, sd_data, CV_data])
```

In the next cell, titled _Perform statistics_

**Replace** lines 1-15, which is this:
```
# Convert to DataFrame and save to CSV
df_stats = pd.DataFrame(data_stats, columns=['Subject', 'Shim_Mode', 'Average', 'Standard_Deviation'])
df_stats.to_csv(os.path.join(path_results, 'stats_b1plus.csv'), index=False)

# Compute statistics across subjects
grouped_means = df_stats.groupby('Shim_Mode').agg({'Average': ['mean', 'std'], 'Standard_Deviation': ['mean', 'std']})

# Format mean ± standard deviation
grouped_means['Average_formatted'] = grouped_means['Average']['mean'].map("{:.2f}".format) + " ± " + grouped_means['Average']['std'].map("{:.2f}".format)
grouped_means['Standard_Deviation_formatted'] = grouped_means['Standard_Deviation']['mean'].map("{:.2f}".format) + " ± " + grouped_means['Standard_Deviation']['std'].map("{:.2f}".format)

# Drop multi-level index and only keep formatted columns
grouped_means = grouped_means.drop(columns=['Average', 'Standard_Deviation'])
grouped_means.columns = ['Average', 'Standard_Deviation']  # Rename columns for clarity
grouped_means.reset_index().to_csv(os.path.join(path_results, 'stats_b1plus_average_across_subjects.csv'), index=False)
```

With this:

```
# Convert to DataFrame and save to CSV
df_stats = pd.DataFrame(data_stats, columns=['Subject', 'Shim_Mode', 'Average', 'Standard_Deviation', 'CV'])
df_stats.to_csv(os.path.join(path_results, 'stats_b1plus.csv'), index=False)

# Compute statistics across subjects
grouped_means = df_stats.groupby('Shim_Mode').agg({'Average': ['mean', 'std'], 'Standard_Deviation': ['mean', 'std'],'CV': ['mean', 'std']})

# Format mean ± standard deviation
grouped_means['Average_formatted'] = grouped_means['Average']['mean'].map("{:.2f}".format) + " ± " + grouped_means['Average']['std'].map("{:.2f}".format)
grouped_means['Standard_Deviation_formatted'] = grouped_means['Standard_Deviation']['mean'].map("{:.2f}".format) + " ± " + grouped_means['Standard_Deviation']['std'].map("{:.2f}".format)
grouped_means['CV_formatted'] = grouped_means['CV']['mean'].map("{:.2f}".format) + " ± " + grouped_means['CV']['std'].map("{:.2f}".format)

# Drop multi-level index and only keep formatted columns
grouped_means = grouped_means.drop(columns=['Average', 'Standard_Deviation','CV'])
grouped_means.columns = ['Average', 'Standard_Deviation','CV']  # Rename columns for clarity
grouped_means.reset_index().to_csv(os.path.join(path_results, 'stats_b1plus_average_across_subjects.csv'), index=False)

```

**Sanity check:**

The end result, the table grouped_means, should look like this:

image

**Comment by dpapp86** [comment]
@agahkarakuzu gentle ping

**Comment by agahkarakuzu** [comment]
@dpapp86 will try to get to this today. Thanks for the reminder!

**Comment by agahkarakuzu** [comment]
@dpapp86 `stats_b1plus_average_across_subjects.csv`

image

Changes are on my `agah-patch1` branch, will push there if this looks good to you. 

BTW, to test these, I am changing notebook locally, then uploading it to https://preprint.neurolibre.org/10.55458/neurolibre.00025/ binderhub session to generate new outputs. It comes in pretty handy as I don't have this data etc locally on my computer!

**Comment by agahkarakuzu** [comment]
https://github.com/shimming-toolbox/rf-shimming-7t/pull/100/commits/453b91d3cdc3809f65ba94516feb851e51e559e2

To be merged via #100.

Feel free to close this one if there are no other changes.

**Comment by dpapp86** [comment]
Have you added in the common scales for the B1+/contrast figure?

**Comment by agahkarakuzu** [comment]
image
image
image

@dpapp86 I'll push it if looks ok.

**Comment by dpapp86** [comment]
Awesome, thank you so much!!

Punch it!

**Pull request closed without merging**
